name: musicavis
description: Become more efficient with your music practice sessions.
version: 1.0.0+1

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

environment:
  sdk: ">=2.10.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  another_flushbar: ^1.10.4
  flutter_launcher_icons: ^0.8.1
  flutter_riverpod: ^0.12.2
  flutter_slidable: ^0.5.7
  graphic: ^0.3.0
  hive: ^1.4.4+1
  hive_flutter: ^0.3.1
  hooks_riverpod: ^0.12.2
  intl: ^0.16.1
  launch_review: ^2.0.0
  month_picker_dialog: ^0.3.3
  table_calendar: ^2.3.3
  url_launcher: ^5.7.10

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^1.10.13
  hive_generator: ^0.8.2

flutter:
  uses-material-design: true
  assets:
    - assets/instruments.txt

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icon/icon.png"
